### ISSUE TITLE
Google store address not working?

### ISSUE THREAD

**Issue by fqxufo** [scarsu/NotionX#1]
The url just redirect to github ,not the google chrome store. Not submitting to the store?

Maybe consider the firefox extension store? It's free of charge

**Comment by scarsu** [comment]
Yesterday NotionX 1.0.0 had been submitted to addons.mozilla.org and Chrome Web Store.Now it's pending to be reviewed and signed.

This process could take a few extra hours and up to a couple of days. Due to disruptions caused by the COVID-19 pandemic, it may take up to a week.

![image](https://user-images.githubusercontent.com/19526406/100696185-f106d080-33cd-11eb-937f-091e57db02e1.png)

![image](https://user-images.githubusercontent.com/19526406/100696221-04b23700-33ce-11eb-9f44-0901db92e519.png)

**Comment by scarsu** [comment]
FireFox approved🎉， [Link](https://addons.mozilla.org/firefox/addon/notionx/), [Download](https://scarsu.oss-cn-shanghai.aliyuncs.com/notionx/notionx-1.0.0-fx.xpi)
